---
title: "LN2 RNA extraction 04232026"
---

## Goal

- Test the use of liquid nitrogen to flash-freeze samples with large amount of blood and then cut with a razor blade. This was done to possibly help with homogenization and thus create a higher yield

## Samples used:

- LC-EESC-1986e - Fish crow blood sample in DNA/RNA Shield (I think?).
  - Note: Did not use enough LN2 to freeze sample. Used razor to cut up clot and split across 2 tubes
- RCKI 2A1 - LN2 cut control
- RCKI 2A3 - Normal RNA extraciton protocol control. No freezing
- LCEESC-1985e - Fish crow blood sample in DNA/RNA Shield. This one was properly frozen and cut with razor blade.

## Protocol Notes

- Followed the [Tri-Reagent/Direct-zol RNA Isolation Protocol](https://github.com/JAHarvey/RNA-Blood-preservation-extraction/blob/main/RNA_Isolation_Protocol.mkd) with modifications to test LN2 flash freezing

- **All surfaces and tubes were sprayed with RNAse-Zap prior to use and between samples**. Forceps were sterilized with 10% bleach solution and then RNAse-zap between samples.

- While sample was still almost entirely frozen, used needle-tip forceps to remove sample from tube and placed on RNAse-free parafilm.

  - Note: parafilm is not a good surface for doing this. Became very brittle and cracked from LN2 exposure. Possible that small fragments of parafilm made it into tubes for homogenization.
  - Note: LC-EESC-1985e sample broke during removal with forceps. Conical bottom tubes (as oppsed to more wide-bottomed tubes) are difficult to remove entire sample from. Proceeded only with section that was broken off form conical bottom, as this was still a large volume of sample.

- Once sample was on parafilm, \~1mL of LN2 was poured over the sample up to 4 times to ensure sample was properly frozen.

  - Note: For LC-EESC-1986e, only 1mL of LN2 total was used and this was not nearly enough.

- Approximately 30uL of RCKI 2A1 was cut from the frozen sample and placed in 1200uL of Tri-Reagent in a snap-lock tube with 1 metal bead. Remaineder of the sample was returned to the tube and placed back at -80C

- Approximately 40uL of LC-EESC-1985e was cut from the frozen sample and placed in 1200uL of Tri-Reagent in a snap-lock tube with 1 metal bead. Remainder of the sample was returned to the tube and placed back at -80C

- Used 100uL of RCKI 2A3, as the sample was fully lysed and could not be spun down. Unclear if sample was stored in DNA/RNA shield or RNAlater.

- Both of the LC-EESC-1986e samples were placed in 1200uL total Tri-Reagent.

- Tissuelyzer adapters were pre-cooled at -80C.

  - Note: This is likely too cold for use with Tri-Reagent. Samples were freezing while on the Tissuelyzer instrument and the metal bead was being frozen in place.

- Swapped out chilled tube adapter for tissuelyzer with a room temperature one, but kept chilled lids to reduce overheating but prevent freezing.

- RCKI controls and LC-EESC-1986e tube 1 were well homogenized after 6 30 second runs at 20Hz.

  - LC-EESC-1986e tube 2 and LC-EESC-1985e were given 2 additional runs to increase homogenization. LC-EESC-1985e continued to contain a large clot that would not homogenize. It is possible that trimming the sample does not make a large impact, or that more beads are necessary.
  - LC-EESC-1985e was given a second metal bead for its final 30sec run on the tissue lyzer but this did not impact the size of the clot.
  - Both RCKI samples were still very pink after homogenization and likely did not contain a lot of blood.

## Concentrations

| Sample         | ng/uL |
|----------------|-------|
| LC-EESC-1986e1 | 23    |
| LC-EESC-1986e2 | 38    |
| LC-EESC-1985e  | 7.24  |
| RCKI 2A1       | 2.08  |
| RCKI 2A3       | \<2   |
