---
title: "OSPR_extraction_05212026"
---

## Goal: Extract RNA from Osprey blood. Try to standardize clot input size.

## Samples:

| Sample tube | Temp tube name | Aqueous vol collected (uL) | Qubit Concentration (ng/uL) |
|----|----|----|----|
| 24JH00047 | 47.1 | 710 | 174 |
|  | 47.2 | 520 | 110 |
| 24JH00056 | 56.1 | 660 | 412 |
|  | 56.2 | 655 | 443 |
| 24JH00038 | 38.1 | 640 | 107 |
|  | 38.2 | 640 | 65.5 |

## Protocol/Notes

- Used standard RNA extraction protocol from blood clots.

- samples 47 and 56 were not well shaken after collection. 47 more so, with the RNA/DNA shield not having any red tint to it.

- Took 4 minutes to process all samples to 4C incubation step

- Ran samples 8x on the tissuelyzer instead of 6. Forgot to flip the tissuelyzer adapter after 3 intervals, swapped instead at 6. Samples looked well homogenized with the exception of 24JH00047 samples which I ran for a 9th interval. They looked well homogenized at that point. The lag in homogenization may have been due to me not rotating the adapter block.

- Treated samples with DNase resuspended by Abbey
