---
title: "DNA extraction for samples in DNA/RNA Shield"
format:
  html: default
  pdf: default
---

Protocol for use of Zymo Research [Quick-DNA Miniprep plus kit](https://files.zymoresearch.com/protocols/_d4068_d4069_quick-dna_miniprep_plus_kit.pdf) for extracting DNA from Nucleated Turkey Blood samples.

## Materials

-   Zymo Research Quick-DNA Miniprep plus kit
-   Whole Blood sample preserved in RNA/DNA shield
-   1000uL pipette w/ tips
-   200uL pipette w/ tips
-   20uL pipette w/ tips
-   Microfuge tube rack
-   Eppendorf tubes

## For Lysed Samples in DNA RNA shield

-  [ ] 1. Thaw sample entirely and vortex briefly to make sure sample is homogenous.

-  [ ] 2. Take 200uL of sample and transfer to a DNase-free 1.7mL tube. Add 10uL of Proteinase K to this sample. - Note: If no wide-aperature 1000uL pipette tips are available, gently but quickly tap the bottom of the sample tube with the pipette tip as you draw up the sample. This helps move the sample into the pipette so you get the full 200uL.

-  [ ] 3. Vortex for 10-15 seconds to mix thoroughly and incubate at room temperature for 3 hours or overnight. - Note: Need to test overnight digestion. Normal processing protocal allows for overnight digestion at 55C.

-   [ ] 4. Add 1 volume (210uL for maximum input volume) of Genomic Binding Buffer to the digested sample. Vortex for 10-15 seconds.
-   [ ] 5. Transfer mixture to a Zymo-Spin IIC-XLR Column in a collection tube. Centrifuge at \>= 12,000xg for 1 minute or until completely cleared. Discard the flow through and collection tube.
-   [ ] 6. Add 400uL **DNA Pre-Wash Buffer** to the spin column in a **new** collection tube. Centrifuge at \>=12,000xg for 1 minute. Empty the collection tube.
-   [ ] 7. Add 700uL **g-DNA Wash Buffer** to the spin column. Centrifuge at \>= 12,000xg for 1 minute. Empty the collection tube.
-   [ ] 8. Add 200uL **g-DNA Wash Buffer** to the spin column. Centrifuge at \>=12,000xg for 1 minute. Discard the collection tube and flow through.
-   [ ] 9. Transfer the spin column to a clean microcentrifuge tube. Add 50uL of DNA Elution Buffer or Nuclease-free water directly to the matrix. Incu bate for 5 minutes at room temperature, then centrifuge at maximum speed for 1 minute to elute the DNA. Teh eluted DNA can be used immediately for molecular based applications or stored at \<= -20C for future use

## For Nucleated Blood Pellets

-   [ ] 1. Thaw sample completely and centriguge at 5,000xg for 30 seconds to pellet blood cells.

-   [ ] 2. While smaple is thawing, prepare the following in a separate 1.7mL microcentrifuge tube:

    |                              |       |
    |------------------------------|-------|
    | BioFluid & Cell Buffer (Red) | 200uL |
    | ProteinaseK                  | 20uL  |
    | DNA Elution Buffer           | 200uL |

-   [ ] 3. Placing the tip of a pipette at the bottom of the sample tube, **slowly** draw up 10uL of blood from the pellet at the bottom of the tube. Do you best not to draw up any DNA/RNA Shield. **Slowly** dispense the blood into the tube you prepared previously.

-   [ ] 4. Mix tube thoroughly then incubate at 55C for 20 minutes or overnight.

-   [ ] 5. Add 1 volume of Genomic Binding Buffer to the tube and mix thoroughly by pipetting up and down **and** by vortexing. Ensure the sample is homogenous before continuing.

-   [ ] 6. Transfer the mixture to a Zymo-Spin IIC-XLR Column in a Collection tube. Centrifuge at \>=12,000xg for 1 minute or until the whole sample has passed through. Discard the Collection Tube with the flow through.

-   [ ] 7. Add 400uL **DNA Pre-Wash** to the spin column in a new collection tube. Centriuge at \>=12,000xg for 1 minute. Empty the collection tube.

-   [ ] 8. Add 700uL **g-DNA Wash Buffer** to the sping column. Centrifuge at \>=12,000xg for 1 minute. Empty the Collection tube.

-   [ ] 9. Add 200uL **g-DNA Wash Buffer** to the spin column directly on the matrix. Centrifuge at \>=12,000xg for 1 minute. Discard the collection tube and flow through.

-   [ ] 10. Transfer the spin column to a fresh DNase-free 1.7uL microfuge tube. Add 50uL **DNA Elution Buffer** or Nuclease-Free water directly on the matrix. Incubate for 5 minutes at room temperature, the centrifuge at top speed for 1 minute to elute the DNA. The eluted DNA can be used immediately for molecular based applications or stored at \<=-20C for future use.

## Protocol Notes

-   If using a sample input of \<50uL for the lysed sample protocol, increase volume to 50uL using DNA Elution Buffer or an isotonic buffer like PBS before continuing.
