---
title: "Turkey DNA extraction"
date: 03-10-2026
---

## Goal

Test 3 hour and overnight ProteinaseK digestion on gDNA extraction from RI turkey samples.

## 03-09-2026

Samples used:

| 3 Hour digestion | Overnight digestion |
|------------------|---------------------|
| RDM007           | RDM010              |
| RDM008           | RDM011              |
| RDM009           | RDM012              |

Followed [gDNA extraction protocol](https://github.com/JAHarvey/HarveyLabNotebook/blob/cb09ce07c26d0a2255f25cf7821924b421649d7e/Niel%20Bauer%20Lab%20Notebook/DNA_extraction_protocol.qmd) with any changes or observations noted below.

-   Since no wide-aperature 1000uL pipette tips were available, I found that tapping the tip against the bottom of the tube while drawing up sample helped me gather the full 200uL despite the viscosity of the sample. 
-   Centrifuged samples 7 and 9 a second time on step 5 as some sample was still retained in the column after the first spin.
-   Centrifuged all 3 hour samples a second time after adding the Pre-Wash buffer as some was still retained in the column.

## 03-10-2026
-   Overnight incubation was a total of 14 hours.
  -   Placed a tube rack on top of the tubes during the overnight incubation to ensure that the caps did not pop open from pressure build up.
-   Centrifuged all overnight samples a second time on step 5 as some sample was retained in the column. 