project:
  type: website

website:
  title: "Niel Bauer Lab Notebook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Experiments.qmd
        text: Experiments
      - href: Protocols.qmd
        text: Protocols
      

format:
  html:
    theme: 
      light: flatly
      dark: darkly

editor: visual

